version: "3.8"
services:
  app:
    build: .
    image: crud
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 60s
    container_name: curd
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: crud
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
